on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - aat/cross-compile-cgo-darwin
name: Canary
jobs:
  canary:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build Hermit
        run: |
          make GOARCH=amd64 CHANNEL=canary build
          make GOARCH=arm64 CHANNEL=canary build
          go run ./cmd/geninstaller --dest=build/install.sh --dist-url=https://github.com/cashapp/hermit/releases/download/canary
      - name: Release canary
        uses: ncipollo/release-action@v1
        with:
          tag: canary
          name: Canary
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
