on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master
name: Docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Generate Github App Access Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Update git config
        run: git config --global url."https://x-oauth-token:${TOKEN}@github.com/squareup".insteadOf https://github.com/squareup
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Generate Schema Docs
        run: |
          ./bin/make -C docs schema
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          siteDir: /github/workspace/docs

