on:
  push:
    paths-ignore:
      - 'docs/**'
    tags:
      - 'v*'
name: Release
jobs:
  deployable:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build Hermit
        run: |
          make GOARCH=amd64 CHANNEL=stable build
          make GOARCH=arm64 CHANNEL=stable build
          go run ./cmd/geninstaller --dest=build/install.sh --dist-url=https://github.com/cashapp/hermit/releases/download/stable
      - name: Release versioned
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release stable
        uses: ncipollo/release-action@v1
        with:
          tag: stable
          name: Stable
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
