on:
  schedule:
    - cron: "0 0 * * *"
name: Scheduled Sanity Test
jobs:
  test:
    name: Full Sanity Test
    strategy:
      matrix:
        os: [ ubuntu-16.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Test packages
      run: |
        cd it/sanity
        CHANGES=$(git log master --raw --since="25 hours ago" | wc -l)
        if [ $CHANGES != "0" ]; then
          ./run.sh -a
        else
          echo "No changes in 25 hours to Hermit. Skipping test"
        fi
